# Generated by Django 4.1.1 on 2022-09-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CourseName", models.CharField(max_length=20)),
                (
                    "Duration",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
            ],
            options={"db_table": "coursestream",},
        ),
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type", models.CharField(max_length=20)),
            ],
            options={"db_table": "coursetype",},
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("IsActive", models.BooleanField(default=False)),
                ("DateCreated", models.DateTimeField(auto_now_add=True)),
                ("DateUpdated", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="avatar.png", upload_to="profiles/"),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=25)),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("Country", models.CharField(blank=True, default="", max_length=30)),
                ("State", models.CharField(blank=True, default="", max_length=30)),
                ("City", models.CharField(blank=True, default="", max_length=30)),
                ("Address", models.TextField(blank=True, default="", max_length=255)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.master",
                    ),
                ),
            ],
            options={"db_table": "profile",},
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=15)),
                ("URL", models.URLField(unique=True)),
            ],
            options={"db_table": "sociallink",},
        ),
        migrations.CreateModel(
            name="UniversityBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UniversityBoardName", models.CharField(max_length=100)),
            ],
            options={"db_table": "UniversityBoard",},
        ),
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserID", models.CharField(max_length=20)),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
                (
                    "SocialLink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.sociallink",
                    ),
                ),
            ],
            options={"db_table": "socialprofile",},
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Skill", models.CharField(max_length=25)),
                (
                    "Level",
                    models.CharField(
                        choices=[
                            (35, "beginner"),
                            (70, "intermediate"),
                            (100, "advance"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
            ],
            options={"db_table": "skill",},
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PersonName", models.CharField(max_length=25)),
                ("JobProfile", models.CharField(max_length=25)),
                ("Contact", models.EmailField(max_length=254)),
                ("LinkedIn", models.URLField()),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
            ],
            options={"db_table": "reference",},
        ),
        migrations.CreateModel(
            name="ProjectPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProjectImage",
                    models.FileField(default="project.png", upload_to="projects/"),
                ),
                ("ProjectName", models.CharField(max_length=30)),
                ("Description", models.TextField(max_length=255)),
                ("ProjectDate", models.DateField()),
                ("IsContinue", models.BooleanField(default=False)),
                ("ProjectURL", models.URLField(default="")),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
            ],
            options={"db_table": "projectportfolio",},
        ),
        migrations.CreateModel(
            name="HobbiesInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=15)),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
            ],
            options={"db_table": "hobbiesinterest",},
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CompanyName", models.CharField(max_length=100)),
                ("Designation", models.CharField(max_length=50)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("IsContinue", models.BooleanField(default=False)),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
            ],
            options={"db_table": "experience",},
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("IsContinue", models.BooleanField(default=False)),
                ("Score", models.DecimalField(decimal_places=2, max_digits=3)),
                ("IsCGPA", models.BooleanField(default=False)),
                (
                    "CourseStream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.coursestream",
                    ),
                ),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
                (
                    "UniversityBoard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.universityboard",
                    ),
                ),
            ],
            options={"db_table": "education",},
        ),
        migrations.AddField(
            model_name="coursestream",
            name="CourseType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ResumeApp.coursetype"
            ),
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=25)),
                ("Year", models.CharField(max_length=4)),
                ("Issuer", models.CharField(max_length=25)),
                ("VerificationURL", models.URLField(default="")),
                (
                    "Profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ResumeApp.profile",
                    ),
                ),
            ],
            options={"db_table": "certification",},
        ),
    ]
