# Generated by Django 4.1.2 on 2022-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Known',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
